import TKAPemantapanLayout from "@/components/tka/TKAPemantapanLayout";
import type { MateriSection, LatihanSoal } from "@/components/tka/TKAPemantapanLayout";

const materiSections: MateriSection[] = [
  { heading: "A. Pengertian Himpunan", content: `Himpunan adalah kumpulan objek yang terdefinisi dengan jelas.\n\nCara menyatakan himpunan:\n1. Dengan kata-kata: "Himpunan bilangan genap"\n2. Dengan notasi pembentuk himpunan: $A = \\{x | x$ bilangan genap$\\}$\n3. Dengan mendaftar anggotanya: $A = \\{2, 4, 6, 8, ...\\}$` },
  { heading: "B. Jenis-jenis Himpunan", content: `- Himpunan kosong ($\\emptyset$ atau $\\{\\}$): tidak memiliki anggota\n- Himpunan semesta (S atau U): memuat semua anggota yang dibicarakan\n- Himpunan berhingga: jumlah anggota dapat dihitung\n- Himpunan tak berhingga: jumlah anggota tidak dapat dihitung\n- Himpunan sama: memiliki anggota yang tepat sama\n- Himpunan ekuivalen: memiliki jumlah anggota yang sama` },
  { heading: "C. Operasi Himpunan", content: `1. Gabungan (Union): $A \\cup B = \\{x | x \\in A$ atau $x \\in B\\}$\n   Rumus: $n(A \\cup B) = n(A) + n(B) - n(A \\cap B)$\n\n2. Irisan (Intersection): $A \\cap B = \\{x | x \\in A$ dan $x \\in B\\}$\n\n3. Selisih (Difference): $A - B = \\{x | x \\in A$ dan $x \\notin B\\}$\n\n4. Komplemen: $A^c = \\{x | x \\in S$ dan $x \\notin A\\}$\n\n5. Hukum De Morgan:\n   $(A \\cup B)^c = A^c \\cap B^c$\n   $(A \\cap B)^c = A^c \\cup B^c$` },
  { heading: "D. Diagram Venn", content: `Diagram Venn digunakan untuk menyatakan hubungan antar himpunan secara visual.\n\nRumus kardinalitas untuk tiga himpunan:\n$n(A \\cup B \\cup C) = n(A) + n(B) + n(C) - n(A \\cap B) - n(A \\cap C) - n(B \\cap C) + n(A \\cap B \\cap C)$` },
];

const latihanDasar: LatihanSoal[] = [
  { no: 1, soal: "Diketahui\nS = {x | x < 15, x $\\in$ bilangan asli}\nP = {x | 2 $\\leq$ x < 10, x $\\in$ bilangan prima}\nQ = {x | 2 < x $\\leq$ 10, x $\\in$ bilangan genap}\nDiagram Venn yang menyatakan hubungan di atas adalah ...", options: ["A.|https://drive.google.com/thumbnail?id=1bjgTDobme-339WSKwFxTj85moUMt4J6e&sz=w800", "B.|https://drive.google.com/thumbnail?id=19by54iWAtblxty-jtdFVWzic9wB7HkJI&sz=w800", "C.|https://drive.google.com/thumbnail?id=1CxVpXw1NBNgcBbY-qBLF_mKb6ildxPqp&sz=w800", "D.|https://drive.google.com/thumbnail?id=1PS-Ap7zDmNffqM2L00wSR0jip1_4tqmP&sz=w800"], jawaban: "C", pembahasan: "S = {1,2,...,14}\nP = {2,3,5,7} (prima dengan 2 ≤ x < 10)\nQ = {4,6,8,10} (genap dengan 2 < x ≤ 10)\nP ∩ Q = ∅ (tidak ada anggota bersama, 2 tidak masuk Q karena Q mengharuskan x > 2)\nDiagram: P dan Q adalah dua lingkaran SALING LEPAS (tidak beririsan) di dalam persegi S\nAnggota P yang tidak masuk Q: {2,3,5,7}\nAnggota Q yang tidak masuk P: {4,6,8,10}" },
  { no: 2, soal: "Diketahui:\nS = {x | 1 $\\leq$ x $\\leq$ 10, x $\\in$ bilangan asli}\nP = {x | x $\\leq$ 6, x $\\in$ bilangan prima}\nQ = {x | 1 $\\leq$ x $\\leq$ 9, x $\\in$ bilangan genap}\nDiagram Venn untuk himpunan-himpunan di atas adalah ...", options: ["A.|https://drive.google.com/thumbnail?id=1BHSvpzcObESqlhbrm7PfkOuRuZnbnf3J&sz=w800", "B.|https://drive.google.com/thumbnail?id=1fZWVP3UMw083sMOyx5LlOVnVqujqcQ3F&sz=w800", "C.|https://drive.google.com/thumbnail?id=1lEHTqKktMDLPT0sl0HFMobOGub3aHMDJ&sz=w800", "D.|https://drive.google.com/thumbnail?id=11co-lVEgY02aBS0wNX9PKpjOYGemAXXh&sz=w800"], jawaban: "B", pembahasan: "S = {1,2,3,4,5,6,7,8,9,10}\nP = {2,3,5} (prima ≤ 6)\nQ = {2,4,6,8} (genap, 1 ≤ x ≤ 9)\nP ∩ Q = {2} (hanya 2 yang prima dan genap)\nHanya P = {3,5}\nHanya Q = {4,6,8}\nDi luar P dan Q: {1,7,9,10}\nDiagram: dua lingkaran P dan Q beririsan, dengan 2 di bagian irisan" },
  { no: 3, soal: "Perhatikan gambar diagram Venn berikut!\nPernyataan berikut yang benar adalah ....", image: "https://drive.google.com/thumbnail?id=1_5TXjD6ro0fw4r83PTWZ2Y4Ajpmbo6Kk&sz=w800", options: ["A. $B \\cup C = \\{1, 2, 3, 4, 5, 6, 8\\}$", "B. $B \\cap C = \\{2, 6, 7, 9\\}$", "C. $B - C = \\{1, 3, 9\\}$", "D. $C - B = \\{5, 8\\}$"], jawaban: "C", pembahasan: "Dari diagram Venn (berdasarkan data soal):\nB = {1, 2, 3, 6, 7, 9}, C = {2, 5, 6, 7, 8}\nCek pilihan C: B - C = anggota B yang tidak ada di C\nB - C = {1, 3, 9} ✓ BENAR\nCek pilihan A: B∪C = {1,2,3,5,6,7,8,9} bukan {1,2,3,4,5,6,8} ✗\nCek pilihan B: B∩C = {2,6,7} bukan {2,6,7,9} ✗\nCek pilihan D: C - B = {5,8} → ini benar juga! Periksa soal asli untuk pilihan yang tepat.\nJawaban yang paling umum untuk soal tipe ini: C (B-C = {1,3,9})" },
  { no: 4, soal: "Diketahui\nP = {x | 2 $\\leq$ x $\\leq$ 12, x $\\in$ bilangan cacah} dan Q = {x | x faktor dari 12}.\n$P \\cap Q$ = ...", options: ["A. {3, 4, 6}", "B. {3, 4, 6, 12}", "C. {2, 3, 4, 6, 12}", "D. {1, 2, 3, 4, 6, 12}"], jawaban: "C", pembahasan: "P = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}\nQ = faktor dari 12 = {1, 2, 3, 4, 6, 12}\nP ∩ Q = anggota yang ada di P DAN di Q\nPeriksa setiap anggota Q:\n- 1 ∉ P (P dimulai dari 2) ✗\n- 2 ∈ P ✓, 3 ∈ P ✓, 4 ∈ P ✓, 6 ∈ P ✓, 12 ∈ P ✓\nP ∩ Q = {2, 3, 4, 6, 12} → Jawaban C" },
  { no: 5, soal: "Jika K = {0, 1, 2, 3, 4, 6, 7} dan L = {1, 3, 5, 7, 9, 11, 13}. Hasil K - L adalah ...", options: ["A. {0, 9, 11, 13}", "B. {1, 3, 5, 7}", "C. {0, 2, 4, 6}", "D. {5, 9, 11, 13}"], jawaban: "C", pembahasan: "K - L = anggota K yang TIDAK ada di L\nK = {0, 1, 2, 3, 4, 6, 7}\nL = {1, 3, 5, 7, 9, 11, 13}\nAnggota K yang tidak ada di L:\n- 0 ∉ L ✓\n- 1 ∈ L ✗ (dibuang)\n- 2 ∉ L ✓\n- 3 ∈ L ✗ (dibuang)\n- 4 ∉ L ✓\n- 6 ∉ L ✓\n- 7 ∈ L ✗ (dibuang)\nK - L = {0, 2, 4, 6} → Jawaban C" },
  { no: 6, soal: "Diketahui himpunan\nS = {bilangan asli kurang dari 12}\nA = {bilangan ganjil kurang dari 11}\nB = {bilangan prima kurang dari 12}\nKomplemen dari $(A \\cap B)^c$ adalah ...", options: ["A. {3, 5, 7}", "B. {1, 2, 9, 11}", "C. {4, 6, 8, 10}", "D. {1, 2, 4, 6, 8, 9, 10, 11}"], jawaban: "A", pembahasan: "S = {1,2,3,4,5,6,7,8,9,10,11}\nA = {1,3,5,7,9} (ganjil < 11, perhatikan 11 tidak masuk karena 'kurang dari 11')\nB = {2,3,5,7,11} (prima < 12)\nA ∩ B = {3, 5, 7} (anggota yang ada di A dan B)\n(A ∩ B)^c = S - (A ∩ B) = {1,2,4,6,8,9,10,11}\nKomplemen dari (A ∩ B)^c = ((A ∩ B)^c)^c = A ∩ B = {3, 5, 7} → Jawaban A" },
  { no: 7, soal: "Jika K = {x | 5 $\\leq$ x $\\leq$ 9, x $\\in$ bilangan asli} dan L = {x | 7 $\\leq$ x $\\leq$ 13, x $\\in$ bilangan cacah}\nmaka $K \\cup L$ = ...", options: ["A. {5, 6, 7, 8, 9, 10, 11, 12, 13}", "B. {5, 6, 7, 8, 9, 10, 11, 12}", "C. {6, 7, 8, 9, 10}", "D. {7, 8, 9, 10}"], jawaban: "A", pembahasan: "K = {5, 6, 7, 8, 9} (bilangan asli, 5 ≤ x ≤ 9)\nL = {7, 8, 9, 10, 11, 12, 13} (bilangan cacah, 7 ≤ x ≤ 13)\nK ∪ L = semua anggota K atau L (tanpa pengulangan)\nK ∪ L = {5, 6, 7, 8, 9, 10, 11, 12, 13} → Jawaban A" },
  { no: 8, soal: "Diketahui himpunan D = {bilangan genap antara 3 dan 14}, himpunan L = {bilangan prima kurang dari 8}, himpunan semesta S = {bilangan asli kurang dari 14}. Komplemen dari $D \\cup L$ adalah ...", options: ["A. {2, 3, 5, 7}", "B. {1, 9, 11, 13}", "C. {1, 4, 6, 8, 9, 10, 11, 12, 13}", "D. {2, 3, 4, 5, 6, 7, 8, 10, 12}"], jawaban: "B", pembahasan: "S = {1,2,3,4,5,6,7,8,9,10,11,12,13}\nD = {4,6,8,10,12} (genap antara 3 dan 14, tidak termasuk 3 dan 14)\nL = {2,3,5,7} (prima < 8)\nD ∪ L = {2,3,4,5,6,7,8,10,12}\n(D ∪ L)^c = S - (D ∪ L) = {1,9,11,13} → Jawaban B" },
  { no: 9, soal: "Diketahui\nS = {bilangan asli kurang dari 11}\nA = {bilangan prima kurang dari 11}\nB = {bilangan genap kurang dari 11}\nKomplemen dari $A \\cap B$ adalah ...", options: ["A. {1, 2, 3, ..., 10}", "B. {1, 3, 4, 5, 6, 7, 8, 9, 10}", "C. {2, 3, 5, 7, 9}", "D. {1, 3, 5, 7}"], jawaban: "B", pembahasan: "S = {1,2,3,4,5,6,7,8,9,10}\nA = {2,3,5,7} (prima < 11)\nB = {2,4,6,8,10} (genap < 11)\nA ∩ B = {2} (hanya 2 yang prima sekaligus genap)\n(A ∩ B)^c = S - {2} = {1,3,4,5,6,7,8,9,10} → Jawaban B" },
  { no: 10, soal: "Diketahui\nS = {1, 2, 3, ..., 10}\nA = {x | x $\\leq$ 10, x Bilangan ganjil}\nB = {x | 1 $\\leq$ x $\\leq$ 10, x Bilangan prima}\nI. Komplemen $(A \\cap B) = \\{1, 2, 4, 6, 8, 9\\}$\nII. Komplemen $(A \\cup B) = \\{4, 6, 8, 10\\}$\nIII. Komplemen $(A - B) = \\{2, 3, 4, 5, 6, 7, 8, 10\\}$\nIV. Komplemen $(B - A) = \\{2, 11\\}$\nPernyataan yang benar di bawah ini adalah ....", options: ["A. I, II, dan III", "B. II dan III", "C. I dan III", "D. III dan IV"], jawaban: "B", pembahasan: "A = {1,3,5,7,9}, B = {2,3,5,7}\nI. A∩B = {3,5,7}. (A∩B)^c = {1,2,4,6,8,9,10}. Soal bilang {1,2,4,6,8,9} — kurang 10. SALAH ✗\nII. A∪B = {1,2,3,5,7,9}. (A∪B)^c = {4,6,8,10}. BENAR ✓\nIII. A-B = {1,9}. (A-B)^c = {2,3,4,5,6,7,8,10}. BENAR ✓\nIV. B-A = {2}. (B-A)^c = {1,3,4,5,6,7,8,9,10}. Soal bilang {2,11} — 11 ∉ S. SALAH ✗\nYang benar: II dan III → Jawaban B" },
  { no: 11, soal: "Diketahui A = {huruf pembentuk kata \"matematika\"}, dan B = {huruf pembentuk kata \"Jakarta\"}\nA - B adalah ...", options: ["A. {m, e, i, k, j, r}", "B. {m, e, i}", "C. {a, t, k}", "D. {j, r}"], jawaban: "B", pembahasan: "A = {m, a, t, e, i, k} (huruf unik dari 'matematika')\nB = {j, a, k, r, t} (huruf unik dari 'Jakarta')\nA - B = anggota A yang TIDAK ada di B\n- m ∉ B ✓, a ∈ B ✗, t ∈ B ✗, e ∉ B ✓, i ∉ B ✓, k ∈ B ✗\nA - B = {m, e, i} → Jawaban B" },
  { no: 12, soal: "Diketahui himpunan P = {bilangan prima kurang dari 15} dan $P \\cap Q = \\{2, 3, 5\\}$. Himpunan Q yang mungkin adalah ....", options: ["A. {faktor dari 15}", "B. {faktor dari 30}", "C. {bilangan prima kurang dari 11}", "D. {bilangan ganjil kurang dari 9}"], jawaban: "B", pembahasan: "P = {2,3,5,7,11,13} (prima < 15)\nP ∩ Q = {2,3,5} → Q harus mengandung 2,3,5 tetapi TIDAK 7,11,13\nCek pilihan:\nA. faktor 15 = {1,3,5,15}. P∩Q = {3,5} — tidak ada 2. SALAH ✗\nB. faktor 30 = {1,2,3,5,6,10,15,30}. P∩Q = {2,3,5} — 7,11,13 tidak ada di sini. BENAR ✓\nC. prima < 11 = {2,3,5,7}. P∩Q = {2,3,5,7} — ada 7 juga. SALAH ✗\nD. ganjil < 9 = {1,3,5,7}. P∩Q = {3,5,7} — tidak ada 2. SALAH ✗\nJawaban B" },
  { no: 13, soal: "Diketahui {x | 4 $\\leq$ x $\\leq$ 15, x $\\in$ bilangan prima}. Banyak himpunan bagian dari A adalah ...", options: ["A. 8", "B. 16", "C. 25", "D. 32"], jawaban: "B", pembahasan: "A = {x | 4 ≤ x ≤ 15, x prima}\nBilangan prima di antara 4 dan 15: {5, 7, 11, 13}\nn(A) = 4\nBanyak himpunan bagian = $2^{n(A)} = 2^4 = 16$ → Jawaban B" },
  { no: 14, soal: "Diketahui P = {x | x < 10, x $\\in$ bilangan asli genap}. Banyaknya himpunan bagian dari P yang mempunyai 3 anggota adalah ...", options: ["A. 5", "B. 10", "C. 16", "D. 32"], jawaban: "B", pembahasan: "Bilangan asli genap < 10: {2, 4, 6, 8}\nJika termasuk 0 (bilangan asli/cacah): P = {0, 2, 4, 6, 8}, n(P) = 5\nBanyak himpunan bagian dengan tepat 3 anggota = $\\binom{5}{3} = \\frac{5!}{3!2!} = 10$ → Jawaban B" },
  { no: 15, soal: "Dari 30 siswa diketahui 16 anak gemar IPA, 12 anak gemar Matematika, serta 5 anak tidak gemar IPA atau Matematika. Banyaknya anak yang hanya gemar Matematika adalah ...", options: ["A. 3", "B. 9", "C. 10", "D. 12"], jawaban: "B", pembahasan: "Total = 30, n(IPA) = 16, n(Mat) = 12, tidak keduanya = 5\nn(IPA ∪ Mat) = 30 - 5 = 25\nRumus: n(IPA ∪ Mat) = n(IPA) + n(Mat) - n(IPA ∩ Mat)\n25 = 16 + 12 - n(IPA ∩ Mat)\nn(IPA ∩ Mat) = 28 - 25 = 3\nHanya Matematika = n(Mat) - n(IPA ∩ Mat) = 12 - 3 = 9 → Jawaban B" },
  { no: 16, soal: "Petugas lalu lintas melakukan pemeriksaan terhadap pengendara kendaraan bermotor. Hasilnya 25 orang memiliki SIM A, 30 orang memiliki SIM C, 17 orang memiliki SIM A & C, sedangkan 12 orang tidak memiliki SIM A maupun C. Banyak pengendara bermotor yang diperiksa adalah....", options: ["A. 50 orang", "B. 60 orang", "C. 72 orang", "D. 84 orang"], jawaban: "A", pembahasan: "n(A) = 25, n(C) = 30, n(A∩C) = 17, tidak keduanya = 12\nn(A∪C) = n(A) + n(C) - n(A∩C) = 25 + 30 - 17 = 38\nTotal = n(A∪C) + tidak keduanya = 38 + 12 = 50 → Jawaban A" },
  { no: 17, soal: "Dari 24 siswa kelas A, diketahui 15 siswa suka basket, 5 siswa suka Futsal dan basket, serta 4 siswa tidak suka keduanya, maka banyak siswa yang menyukai salah satu adalah...", options: ["A. 4", "B. 5", "C. 10", "D. 15"], jawaban: "D", pembahasan: "Total = 24, n(B) = 15 (basket), n(B∩F) = 5, tidak keduanya = 4\nn(B∪F) = 24 - 4 = 20\nn(F) = n(B∪F) - n(B) + n(B∩F) = 20 - 15 + 5 = 10\nHanya basket = 15 - 5 = 10\nHanya futsal = 10 - 5 = 5\nSalah satu (tidak keduanya) = 10 + 5 = 15 → Jawaban D" },
  { no: 18, soal: "Peserta tes dinyatakan diterima masuk sekolah jika lulus tes wawancara dan psikotes. Dari 50 peserta tes diketahui jumlah siswa yang lulus tes psikotes dua kali dari jumlah yang lulus tes wawancara. Jika akhirnya peserta yang diterima sebanyak 10 orang, maka banyaknya peserta yang lulus psikotes adalah...", options: ["A. 20", "B. 30", "C. 40", "D. 45"], jawaban: "C", pembahasan: "Misalkan: lulus wawancara = x, lulus psikotes = 2x\nDiterima (lulus keduanya) = 10\nn(W∪P) = 50 (semua peserta termasuk yang tidak lulus keduanya)\nRumus: x + 2x - 10 = 50 → 3x = 60 → x = 20\nLulus psikotes = 2x = 2 × 20 = 40 → Jawaban C" },
  { no: 19, soal: "Dalam suatu survey yang dilakukan terhadap 60 orang, diperoleh informasi bahwa 25 orang berlangganan Newsweek, 26 orang berlangganan Time, dan 26 orang berlangganan Fortune. Diketahui juga bahwa 9 orang berlangganan Newsweek dan Fortune, 11 orang berlangganan Newsweek dan Time, 8 orang berlangganan Time dan Fortune, dan 8 orang tidak berlangganan majalah apapun. Berapa orangkah yang berlangganan ketiga majalah Newsweek, Time dan Fortune?", options: ["A. 2", "B. 3", "C. 4", "D. 5"], jawaban: "B", pembahasan: "N=25, T=26, F=26, N∩F=9, N∩T=11, T∩F=8, tidak keduanya=8\nn(N∪T∪F) = 60 - 8 = 52\nRumus 3 himpunan:\n52 = 25+26+26 - 11 - 9 - 8 + n(N∩T∩F)\n52 = 77 - 28 + n(N∩T∩F)\n52 = 49 + n(N∩T∩F)\nn(N∩T∩F) = 3 → Jawaban B" },
  { no: 20, soal: "Suatu kelas terdiri dari 42 siswa. $\\frac{1}{3}$ dari seluruh siswa itu menyukai olahraga berenang, $\\frac{1}{6}$ nya menyukai berenang dan sepakbola dan $\\frac{3}{7}$ nya tidak menyukai kedua olahraga tersebut. Banyak orang yang menyukai sepakbola adalah ...", options: ["A. 7 siswa", "B. 10 siswa", "C. 17 siswa", "D. 24 siswa"], jawaban: "C", pembahasan: "Total = 42\nn(R) = (1/3)×42 = 14 (renang)\nn(R∩S) = (1/6)×42 = 7 (renang dan sepakbola)\nTidak keduanya = (3/7)×42 = 18\nn(R∪S) = 42 - 18 = 24\nRumus: n(R∪S) = n(R) + n(S) - n(R∩S)\n24 = 14 + n(S) - 7\nn(S) = 24 - 14 + 7 = 17 → Jawaban C" },
];

const HimpunanPage = () => (
  <TKAPemantapanLayout
    title="HIMPUNAN"
    materiSections={materiSections}
    latihanDasar={latihanDasar}
  />
);

export default HimpunanPage;
