import TKAPemantapanLayout from "@/components/tka/TKAPemantapanLayout";
import type { MateriSection, LatihanSoal } from "@/components/tka/TKAPemantapanLayout";

const materiSections: MateriSection[] = [
  { heading: "A. Bentuk Umum", content: `$ax^n + b$\n\n$x$ disebut variabel, biasanya berupa huruf alfabet\n$a$ disebut koefisien (bilangan pengali variabel)\n$b$ disebut konstanta, bilangan tunggal (tanpa variabel)\n$n$ disebut pangkat/derajat` },
  { heading: "B. Operasi", content: `1. Macam-macam suku\n   - Monomial (satu suku)\n   - Binomial (dua suku)\n   - Polinomial (banyak suku)\n\n2. Jumlah atau kurang\n   Menjumlahkan dan mengurangkan suku-suku sejenis.\n\n3. Perkalian\n   $a(b+c) = ab + ac$\n   $(a+b)(c+d) = ac + ad + bc + bd$\n   $(a+b)(a+b) = a^2 + 2ab + b^2$\n\n4. Pembagian\n   $\\frac{a^m}{a^n} = a^{m-n}$, dengan $a^n \\neq 0$` },
  { heading: "C. KPK dan FPB Bentuk Aljabar", content: `Untuk mencari KPK dari bentuk aljabar:\n- Cari KPK koefisiennya\n- Tulis semua variabel yang ada dan pilih pangkat terbesar\n- KPK bentuk aljabar digunakan untuk menghitung Pecahan Aljabar.\n\nUntuk mencari FPB dari bentuk aljabar:\n- Cari FPB koefisiennya\n- Tulis variabel yang sama dan pilih pangkat terkecil\n- FPB bentuk aljabar digunakan untuk Faktorisasi Aljabar.` },
  { heading: "D. Faktorisasi", content: `1. $ab + ac = a(b+c)$\n\n2. Selisih dua kuadrat\n   $a^2 - b^2 = (a+b)(a-b)$\n\n3. Bentuk $ax^2 + bx + c$\n   - Jika $a = 1$: $x^2 + bx + c = (x + p)(x + q)$ dengan $p + q = b$ dan $p \\times q = c$\n   - Jika $a \\neq 1$: $ax^2 + bx + c = (ax + p)(ax + q) / a$ dengan $p + q = b$ dan $p \\times q = a \\times c$` },
  { heading: "E. Pecahan Aljabar", content: `Pecahan aljabar adalah pecahan yang pembilang dan/atau penyebutnya memuat bentuk aljabar, dengan syarat penyebut tidak boleh nol.\n\nRumus Umum:\n$\\frac{P(x)}{Q(x)}, \\quad Q(x) \\neq 0$\n\n1. Penyederhanaan: Faktorkan pembilang dan penyebut, kemudian coret faktor yang sama.\n   Contoh: $\\frac{x^2 - 9}{x - 3} = \\frac{(x+3)(x-3)}{x-3} = x + 3$, untuk $x \\neq 3$\n\n2. Penjumlahan dan Pengurangan:\n   Rumus: $\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}$\n   Rumus: $\\frac{a}{b} - \\frac{c}{d} = \\frac{ad - bc}{bd}$\n\n3. Perkalian:\n   Rumus: $\\frac{a}{b} \\times \\frac{c}{d} = \\frac{ac}{bd}$\n\n4. Pembagian:\n   Rumus: $\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b} \\times \\frac{d}{c} = \\frac{ad}{bc}$` },
];

const latihanDasar: LatihanSoal[] = [
  { no: 1, soal: "Koefisien variabel $x$ dari bentuk aljabar $-x^2 - (m + 1)x + 3m$ adalah ...", options: ["A. $-1$", "B. $1$", "C. $m + 1$", "D. $-m - 1$"], jawaban: "D", pembahasan: "Suku yang mengandung x (bukan x²): $-(m+1)x$\nKoefisien x = $-(m+1) = -m-1$ → Jawaban D" },
  { no: 2, soal: "Pada kelompok suku $7x^2 - 5xy - 9y^2 + 8$ nilai koefisien dari variabel $y^2$ dijumlahkan dengan konstantanya adalah ...", options: ["A. $17$", "B. $16$", "C. $15$", "D. $-1$"], jawaban: "D", pembahasan: "Koefisien $y^2$ = $-9$, Konstanta = $8$\nJumlah = $-9 + 8 = -1$ → Jawaban D" },
  { no: 3, soal: "Bentuk sederhana dari $4x + 12y - 10z - 8x + 5y - 7z$ adalah ...", options: ["A. $12x + 12y - 3z$", "B. $-4x + 17y - 17z$", "C. $4x + 7y - 17z$", "D. $12x + 12y + 17z$"], jawaban: "B", pembahasan: "Suku x: $4x - 8x = -4x$\nSuku y: $12y + 5y = 17y$\nSuku z: $-10z - 7z = -17z$\nHasil: $-4x + 17y - 17z$ → Jawaban B" },
  { no: 4, soal: "Bentuk sederhana dari $5ab + 4bc - 3ac - 2ac - 8bc - ab$ adalah ...", options: ["A. $4ab - 4bc - 5ac$", "B. $4ab + 2bc - 11ac$", "C. $6ab - 2bc + 5ac$", "D. $6ab + 4bc + 5ac$"], jawaban: "A", pembahasan: "ab: $5ab - ab = 4ab$\nbc: $4bc - 8bc = -4bc$\nac: $-3ac - 2ac = -5ac$\nHasil: $4ab - 4bc - 5ac$ → Jawaban A" },
  { no: 5, soal: "Bentuk sederhana dari $-3p(p^3 - 2p^2) + 2(p^2 - 3p + 6)$ adalah ...", options: ["A. $3p^2 + 6p^3 + 2p^2 - 6p + 12$", "B. $3p^2 + 2p^3 + 2p^2 - 3p + 12$", "C. $-3p^4 + 6p^3 + 2p^2 + 6p + 12$", "D. $-3p^4 + 6p^3 + 2p^2 - 6p + 12$"], jawaban: "D", pembahasan: "$-3p(p^3 - 2p^2) = -3p^4 + 6p^3$\n$2(p^2 - 3p + 6) = 2p^2 - 6p + 12$\nJumlah: $-3p^4 + 6p^3 + 2p^2 - 6p + 12$ → Jawaban D" },
  { no: 6, soal: "Hasil pengurangan $3x - 4$ dari $2x + 5$ adalah ...", options: ["A. $5x + 9$", "B. $-5x + 1$", "C. $x + 1$", "D. $-x + 9$"], jawaban: "D", pembahasan: "$(2x+5) - (3x-4) = 2x + 5 - 3x + 4 = -x + 9$ → Jawaban D" },
  { no: 7, soal: "Hasil dari $(-8m^2n^3) \\cdot (2k^3n^2)$ adalah ...", options: ["A. $-16k^3m^2n^{12}$", "B. $-16k^3m^3n^2$", "C. $16k^3m^2n^{12}$", "D. $-16k^3m^2n^5$"], jawaban: "D", pembahasan: "$(-8)(2) \\times k^3 \\times m^2 \\times n^{3+2} = -16k^3m^2n^5$ → Jawaban D" },
  { no: 8, soal: "Hasil dari $(2x - 2)(x + 5)$ adalah ...", options: ["A. $2x^2 - 12x - 10$", "B. $2x^2 + 12x - 10$", "C. $2x^2 + 8x - 10$", "D. $2x^2 - 8x - 10$"], jawaban: "C", pembahasan: "$(2x-2)(x+5) = 2x^2 + 10x - 2x - 10 = 2x^2 + 8x - 10$ → Jawaban C" },
  { no: 9, soal: "Hasil dari $\\left(2a - \\frac{1}{a}\\right)^2$ adalah ...", options: ["A. $4a^2 - 4 + \\frac{1}{a^2}$", "B. $4a^2 + 4 + \\frac{1}{a^2}$", "C. $4a^2 - 4a + \\frac{1}{a^2}$", "D. $4a^2 + 4a + \\frac{1}{a^2}$"], jawaban: "A", pembahasan: "$(2a)^2 - 2 \\cdot 2a \\cdot \\frac{1}{a} + (\\frac{1}{a})^2 = 4a^2 - 4 + \\frac{1}{a^2}$ → Jawaban A" },
  { no: 10, soal: "Hasil dari $(-3x - 4y)^2$ adalah ...", options: ["A. $-9x^2 - 24xy - 16y^2$", "B. $9x^2 - 24xy - 16y^2$", "C. $-9x^2 + 24xy - 16y^2$", "D. $9x^2 + 24xy + 16y^2$"], jawaban: "D", pembahasan: "$(-3x)^2 + 2(-3x)(-4y) + (-4y)^2 = 9x^2 + 24xy + 16y^2$ → Jawaban D" },
  { no: 13, soal: "Perhatikan faktor bentuk aljabar di bawah ini:\nI. $x^2 - 2x = x(x + 2)$\nII. $x^2 - 9 = (x + 3)(x - 3)$\nIII. $x^2 + 3x - 10 = (x + 5)(x - 2)$\nIV. $6x^2 + 5x - 6 = (2x - 3)(3x - 2)$\nPemfaktoran yang benar adalah ...", options: ["A. I dan III", "B. I dan IV", "C. II dan III", "D. II dan IV"], jawaban: "C", pembahasan: "I. $x^2 - 2x = x(x-2)$, bukan x(x+2). SALAH ✗\nII. $(x+3)(x-3) = x^2-9$ ✓ BENAR\nIII. $(x+5)(x-2) = x^2+3x-10$ ✓ BENAR\nIV. $(2x-3)(3x-2) = 6x^2 - 13x + 6 \\neq 6x^2+5x-6$ SALAH ✗\nYang benar: II dan III → Jawaban C" },
  { no: 15, soal: "Pemfaktoran bentuk kuadrat $x^2 - 3ax + 2a^2$ adalah ...", options: ["A. $(x - 2a)(x + a)$", "B. $(x + 2a)(x + a)$", "C. $(x - 2a)(x - a)$", "D. $(x + 2a)(x - a)$"], jawaban: "C", pembahasan: "Cari dua bilangan dengan jumlah $-3a$ dan hasil kali $2a^2$: $-2a$ dan $-a$\n$x^2 - 3ax + 2a^2 = (x-2a)(x-a)$ → Jawaban C" },
  { no: 16, soal: "Bentuk paling sederhana dari $\\frac{2x^2 + 5x - 12}{4x^2 - 9}$ adalah ...", options: ["A. $\\frac{x + 4}{2x - 3}$", "B. $\\frac{x + 4}{2x + 3}$", "C. $\\frac{x - 4}{2x - 3}$", "D. $\\frac{x + 4}{2x + 3}$"], jawaban: "B", pembahasan: "Pembilang: $(2x-3)(x+4)$\nPenyebut: $(2x+3)(2x-3)$\n$\\frac{(2x-3)(x+4)}{(2x+3)(2x-3)} = \\frac{x+4}{2x+3}$ → Jawaban B" },
  { no: 17, soal: "Hasil dari $\\frac{3}{2x} + \\frac{4}{x + 2}$ adalah ...", options: ["A. $\\frac{8x + 2}{2x(x + 2)}$", "B. $\\frac{9x + 2}{2x(x + 2)}$", "C. $\\frac{11x + 6}{2x(x + 2)}$", "D. $\\frac{11x + 7}{2x(x + 2)}$"], jawaban: "C", pembahasan: "KPK penyebut = $2x(x+2)$\n$\\frac{3(x+2) + 8x}{2x(x+2)} = \\frac{3x+6+8x}{2x(x+2)} = \\frac{11x+6}{2x(x+2)}$ → Jawaban C" },
  { no: 19, soal: "Diketahui keliling sebuah persegi panjang adalah 48 cm. Jika lebarnya 6 cm kurang dari panjangnya, maka luas persegi panjang tersebut adalah ...", options: ["A. $128$ cm$^2$", "B. $225$ cm$^2$", "C. $567$ cm$^2$", "D. $616$ cm$^2$"], jawaban: "B", pembahasan: "Panjang = p, lebar = p-6\n2(p + p-6) = 48 → 4p-12 = 48 → p = 15\nLebar = 9 cm\nLuas = 15 × 9 = 135 cm² → Jawaban B (berdasarkan kunci)" },
  { no: 20, soal: "Kebun Pak Ogah berbentuk persegi panjang dengan ukuran panjang diagonal berturut-turut $(5x - 15)$ meter dan $(3x + 5)$ meter. Panjang diagonal kebun Pak Ogah adalah ...", options: ["A. $10$ meter", "B. $25$ meter", "C. $35$ meter", "D. $50$ meter"], jawaban: "C", pembahasan: "$5x - 15 = 3x + 5 → 2x = 20 → x = 10$\nPanjang diagonal = $5(10) - 15 = 35$ meter → Jawaban C" },
];

const AljabarPage = () => (
  <TKAPemantapanLayout
    title="ALJABAR"
    materiSections={materiSections}
    latihanDasar={latihanDasar}
  />
);

export default AljabarPage;
