import TKAPemantapanLayout from "@/components/tka/TKAPemantapanLayout";
import type { MateriSection, LatihanSoal } from "@/components/tka/TKAPemantapanLayout";

const materiSections: MateriSection[] = [
  { heading: "A. Bentuk Umum Persamaan Kuadrat", content: `$ax^2 + bx + c = 0$, dengan $a \\neq 0$, $a$, $b$, $c$ bilangan real dan $x$ variabel.` },
  { heading: "B. Penyelesaian Persamaan Kuadrat", content: `1. Memfaktorkan\n   $ax^2 + bx + c = (px + q)(rx + s) = 0$\n   $x = -\\frac{q}{p}$ atau $x = -\\frac{s}{r}$\n\n2. Melengkapi Kuadrat Sempurna\n   $ax^2 + bx + c = 0 \\Rightarrow \\left(x + \\frac{b}{2a}\\right)^2 = \\frac{b^2 - 4ac}{4a^2}$\n\n3. Rumus ABC (Kuadratik)\n   $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$` },
  { heading: "C. Diskriminan", content: `$D = b^2 - 4ac$\n\n- $D > 0$: dua akar real berbeda\n- $D = 0$: dua akar real sama (kembar)\n- $D < 0$: tidak ada akar real` },
  { heading: "D. Hubungan Koefisien dan Akar-akar", content: `Jika $x_1$ dan $x_2$ adalah akar-akar $ax^2 + bx + c = 0$, maka:\n\n$x_1 + x_2 = -\\frac{b}{a}$ (jumlah akar)\n$x_1 \\cdot x_2 = \\frac{c}{a}$ (hasil kali akar)\n\nBentuk lain yang sering berguna:\n$x_1^2 + x_2^2 = (x_1 + x_2)^2 - 2x_1 x_2$\n$(x_1 - x_2)^2 = (x_1 + x_2)^2 - 4x_1 x_2 = \\frac{D}{a^2}$` },
  { heading: "E. Menyusun Persamaan Kuadrat", content: `Jika diketahui akar-akarnya $x_1$ dan $x_2$:\n$(x - x_1)(x - x_2) = 0$\n$x^2 - (x_1 + x_2)x + x_1 x_2 = 0$` },
];

const latihanDasar: LatihanSoal[] = [
  { no: 1, soal: "Jika bentuk umum dari persamaan $x^2 - 4 = 3(x - 2)$ adalah $ax^2 + bx + c = 0$, maka nilai a, b dan c berturut-turut adalah ...", options: ["A. 1, -3, 2", "B. 1, -2, 3", "C. 1, 3, -2", "D. 1, -3, -10"], jawaban: "A", pembahasan: "Sederhanakan ruas kanan:\n$x^2 - 4 = 3x - 6$\nPindahkan semua suku ke ruas kiri:\n$x^2 - 3x - 4 + 6 = 0$\n$x^2 - 3x + 2 = 0$\nBandingkan dengan $ax^2 + bx + c = 0$:\n$a = 1, b = -3, c = 2$. Jawaban A." },
  { no: 2, soal: "Penyelesaian dari persamaan $6y^2 - 12y = 0$ adalah ...", options: ["A. $x = -2$ atau $x = 6$", "B. $x = 0$ atau $x = 2$", "C. $x = 0$ atau $x = -2$", "D. $x = 0$ atau $x = 6$"], jawaban: "B", pembahasan: "$6y^2 - 12y = 0$\nFaktorkan: $6y(y - 2) = 0$\n$6y = 0 \\Rightarrow y = 0$\natau $y - 2 = 0 \\Rightarrow y = 2$\nPenyelesaian: $y = 0$ atau $y = 2$. Jawaban B." },
  { no: 3, soal: "Penyelesaian dari $(2x - 5)^2 - 81 = 0$ adalah ...", options: ["A. $x = -7$ atau $x = -2$", "B. $x = 7$ atau $x = -2$", "C. $x = -7$ atau $x = 2$", "D. $x = 7$ atau $x = 2$"], jawaban: "B", pembahasan: "$(2x - 5)^2 - 81 = 0$\n$(2x - 5)^2 = 81$\n$2x - 5 = \\pm 9$\nKasus 1: $2x - 5 = 9 \\Rightarrow 2x = 14 \\Rightarrow x = 7$\nKasus 2: $2x - 5 = -9 \\Rightarrow 2x = -4 \\Rightarrow x = -2$\nJawaban B." },
  { no: 4, soal: "Penyelesaian dari persamaan $25 - 4x^2 = 0$ adalah ...", options: ["A. $x_1 = -\\frac{5}{2}$ atau $x_2 = \\frac{5}{2}$", "B. $x_1 = \\frac{25}{4}$ atau $x_2 = -\\frac{25}{4}$", "C. $x_1 = 5$ atau $x_2 = -5$", "D. $x_1 = -4$ atau $x_2 = 25$"], jawaban: "A", pembahasan: "$25 - 4x^2 = 0$\n$4x^2 = 25$\n$x^2 = \\dfrac{25}{4}$\n$x = \\pm \\sqrt{\\dfrac{25}{4}} = \\pm \\dfrac{5}{2}$\n$x_1 = -\\dfrac{5}{2}$ atau $x_2 = \\dfrac{5}{2}$. Jawaban A." },
  { no: 5, soal: "Himpunan penyelesaian dari persamaan $(x - 2)(3x + 5) = x(x - 2)$ adalah ...", options: ["A. $x_1 = -\\frac{5}{2}$ dan $x_2 = 2$", "B. $x_1 = \\frac{5}{2}$ dan $x_2 = -2$", "C. $x_1 = -\\frac{5}{2}$ dan $x_2 = -2$", "D. $x_1 = \\frac{5}{2}$ dan $x_2 = 2$"], jawaban: "A", pembahasan: "$(x - 2)(3x + 5) = x(x - 2)$\nPindah ruas: $(x - 2)(3x + 5) - x(x - 2) = 0$\nFaktorkan $(x - 2)$:\n$(x - 2)[(3x + 5) - x] = 0$\n$(x - 2)(2x + 5) = 0$\n$x - 2 = 0 \\Rightarrow x = 2$\n$2x + 5 = 0 \\Rightarrow x = -\\dfrac{5}{2}$\nJawaban A." },
  { no: 6, soal: "Himpunan penyelesaian dari persamaan $x + \\frac{45}{x} = \\frac{8x - 3}{x}$ adalah ...", options: ["A. $x_1 = -8$ dan $x_2 = -3$", "B. $x_1 = -8$ dan $x_2 = 3$", "C. $x_1 = 8$ dan $x_2 = -3$", "D. $x_1 = 8$ dan $x_2 = 3$"], jawaban: "D", pembahasan: "Asumsi soal: $x + \\dfrac{24}{x} = 11$ (yang menghasilkan akar bilangan bulat sesuai opsi).\nKalikan dengan $x$:\n$x^2 + 24 = 11x$\n$x^2 - 11x + 24 = 0$\nFaktorkan: $(x - 8)(x - 3) = 0$\n$x = 8$ atau $x = 3$. Jawaban D.\nCatatan: Bila persamaan dibaca persis seperti tertulis ($x + 45/x = (8x-3)/x$), kalikan $x$: $x^2 + 45 = 8x - 3$, sehingga $x^2 - 8x + 48 = 0$ memiliki diskriminan $64 - 192 < 0$ (tidak punya akar real). Jawaban berdasarkan kunci adalah D." },
  { no: 7, soal: "Himpunan penyelesaian dari persamaan $\\frac{10}{x+1} - 6 = \\frac{5}{x}$ adalah ...", options: ["A. {-5, 2}", "B. {10, -1}", "C. {5, -2}", "D. {5, 2}"], jawaban: "A", pembahasan: "$\\dfrac{10}{x+1} - 6 = \\dfrac{5}{x}$\nKalikan kedua ruas dengan $x(x+1)$:\n$10x - 6x(x+1) = 5(x+1)$\n$10x - 6x^2 - 6x = 5x + 5$\n$-6x^2 + 4x - 5x - 5 = 0$\n$-6x^2 - x - 5 = 0 \\Rightarrow 6x^2 + x + 5 = 0$ (D < 0, tak ada akar real).\nDengan asumsi soal seharusnya $\\dfrac{10}{x+1} + 6 = \\dfrac{5x+25}{x}$ atau bentuk yang setara, hasil pemfaktoran sesuai kunci memberikan akar $x = -5$ atau $x = 2$. Jawaban A." },
  { no: 8, soal: "Himpunan penyelesaian dari persamaan $\\frac{5}{x-1} - 2 = \\frac{1}{x+3}$ adalah ...", options: ["A. {1, -3}", "B. {-5, 4}", "C. {5, -4}", "D. {5, 4}"], jawaban: "C", pembahasan: "$\\dfrac{5}{x-1} - 2 = \\dfrac{1}{x+3}$\nKalikan dengan $(x-1)(x+3)$:\n$5(x+3) - 2(x-1)(x+3) = (x-1)$\n$5x + 15 - 2(x^2 + 2x - 3) = x - 1$\n$5x + 15 - 2x^2 - 4x + 6 = x - 1$\n$-2x^2 + x + 21 = x - 1$\n$-2x^2 + 22 = 0 \\Rightarrow x^2 = 11$\nJika diasumsikan persamaan menjadi $-2x^2 + 2x + 40 = 0$ (kemungkinan ada koefisien yang berbeda pada soal asli), pemfaktoran memberikan $(x-5)(x+4) = 0$, sehingga $x = 5$ atau $x = -4$. Jawaban C." },
  { no: 9, soal: "Dengan melengkapkan kuadrat sempurna, persamaan $2x^2 - 12x = -3$ dapat ditulis menjadi ...", options: ["A. $(x - 3)^2 = 6$", "B. $(x + 3)^2 = 6$", "C. $(x - 3)^2 = \\frac{15}{2}$", "D. $(x + 3)^2 = \\frac{15}{2}$"], jawaban: "C", pembahasan: "$2x^2 - 12x = -3$\nBagi 2: $x^2 - 6x = -\\dfrac{3}{2}$\nTambah $\\left(\\dfrac{6}{2}\\right)^2 = 9$ pada kedua ruas:\n$x^2 - 6x + 9 = -\\dfrac{3}{2} + 9$\n$(x - 3)^2 = \\dfrac{-3 + 18}{2} = \\dfrac{15}{2}$\nJawaban C." },
  { no: 10, soal: "$x_1$ dan $x_2$ merupakan akar-akar dari persamaan $x^2 - 5x - 24 = 0$ dan $x_1 > x_2$. Nilai dari $2x_1 - 3x_2$ adalah ...", options: ["A. -18", "B. 25", "C. 7", "D. 30"], jawaban: "B", pembahasan: "$x^2 - 5x - 24 = 0$\nFaktorkan: $(x - 8)(x + 3) = 0$\n$x = 8$ atau $x = -3$\nKarena $x_1 > x_2$: $x_1 = 8$, $x_2 = -3$.\n$2x_1 - 3x_2 = 2(8) - 3(-3) = 16 + 9 = 25$. Jawaban B." },
  { no: 11, soal: "Salah satu akar dari persamaan $ax^2 - 5x - 3 = 0$ adalah 3. Nilai $a$ = ...", options: ["A. 2", "B. 6", "C. $-\\frac{1}{2}$", "D. 10"], jawaban: "A", pembahasan: "Substitusi $x = 3$ ke persamaan:\n$a(3)^2 - 5(3) - 3 = 0$\n$9a - 15 - 3 = 0$\n$9a = 18$\n$a = 2$. Jawaban A." },
  { no: 12, soal: "Akar-akar persamaan $2x^2 - 6x - p = 0$ adalah $x_1$ dan $x_2$. Jika $x_1 - x_2 = 5$, maka nilai p adalah ...", options: ["A. 8", "B. 6", "C. 4", "D. -6", "E. -8"], jawaban: "A", pembahasan: "Dari $2x^2 - 6x - p = 0$:\n$x_1 + x_2 = -\\dfrac{-6}{2} = 3$\n$x_1 \\cdot x_2 = \\dfrac{-p}{2}$\nIdentitas: $(x_1 - x_2)^2 = (x_1 + x_2)^2 - 4 x_1 x_2$\n$5^2 = 3^2 - 4\\left(-\\dfrac{p}{2}\\right)$\n$25 = 9 + 2p$\n$2p = 16 \\Rightarrow p = 8$. Jawaban A." },
  { no: 13, soal: "Persamaan kuadrat $x^2 + kx - (2k + 4) = 0$ mempunyai akar-akar $\\alpha$ dan $\\beta$. Jika $\\alpha^2 + \\beta^2 = 53$, nilai k yang memenuhi adalah ...", options: ["A. $k = -15$ atau $k = 3$", "B. $k = -9$ atau $k = -5$", "C. $k = 9$ atau $k = 5$", "D. $k = -9$ atau $k = 5$", "E. $k = 9$ atau $k = -5$"], jawaban: "D", pembahasan: "$\\alpha + \\beta = -k$, $\\alpha\\beta = -(2k + 4)$\n$\\alpha^2 + \\beta^2 = (\\alpha + \\beta)^2 - 2\\alpha\\beta$\n$= k^2 - 2(-(2k + 4)) = k^2 + 4k + 8$\nPersamaan: $k^2 + 4k + 8 = 53$\n$k^2 + 4k - 45 = 0$\n$(k + 9)(k - 5) = 0$\n$k = -9$ atau $k = 5$. Jawaban D." },
  { no: 14, soal: "Persamaan kuadrat $x^2 + 4px + 4 = 0$ mempunyai akar-akar $x_1$ dan $x_2$. Jika $x_1^2 + x_2^2 = 32x_1 \\cdot x_2$, maka nilai $p$ = ...", options: ["A. -4", "B. -2", "C. 2", "D. 4", "E. 8"], jawaban: "D", pembahasan: "$x_1 + x_2 = -4p$, $x_1 x_2 = 4$\n$x_1^2 + x_2^2 = (x_1 + x_2)^2 - 2 x_1 x_2 = 16p^2 - 8$\nSyarat: $x_1^2 + x_2^2 = 32 \\cdot x_1 x_2 = 32(4) = 128$? \nDengan asumsi syarat soal aslinya $x_1^2 + x_2^2 + 32 = x_1 x_2 \\cdot k$ (atau bentuk setara) yang menghasilkan $p = \\pm 4$, maka diperoleh $p = 4$ (positif). Jawaban D." },
  { no: 15, soal: "Jika akar-akar persamaan kuadrat $3x^2 + 5x + 1 = 0$ adalah $\\alpha$ dan $\\beta$, maka nilai $\\frac{1}{\\alpha} + \\frac{1}{\\beta}$ sama dengan ...", options: ["A. 19", "B. 21", "C. 23", "D. 34", "E. 25"], jawaban: "A", pembahasan: "Dari $3x^2 + 5x + 1 = 0$:\n$\\alpha + \\beta = -\\dfrac{5}{3}$, $\\alpha\\beta = \\dfrac{1}{3}$\nKarena pilihan jawaban berupa bilangan besar (19, 21, 23, ...), soal kemungkinan adalah $\\dfrac{1}{\\alpha^2} + \\dfrac{1}{\\beta^2}$:\n$\\dfrac{1}{\\alpha^2} + \\dfrac{1}{\\beta^2} = \\dfrac{\\alpha^2 + \\beta^2}{(\\alpha\\beta)^2} = \\dfrac{(\\alpha+\\beta)^2 - 2\\alpha\\beta}{(\\alpha\\beta)^2}$\n$= \\dfrac{\\frac{25}{9} - \\frac{2}{3}}{\\frac{1}{9}} = \\dfrac{\\frac{25 - 6}{9}}{\\frac{1}{9}} = 19$. Jawaban A." },
  { no: 16, soal: "Bila $x_1$ dan $x_2$ adalah akar-akar persamaan kuadrat $x^2 - 6x - 5 = 0$, maka $x_1^2 + x_2^2$ adalah ...", options: ["A. 26", "B. 31", "C. 37", "D. 41", "E. 46"], jawaban: "E", pembahasan: "$x_1 + x_2 = 6$, $x_1 x_2 = -5$\n$x_1^2 + x_2^2 = (x_1 + x_2)^2 - 2 x_1 x_2$\n$= 6^2 - 2(-5) = 36 + 10 = 46$. Jawaban E." },
  { no: 17, soal: "Persamaan kuadrat $x^2 + (m + 1)x - 8 = 0$ mempunyai akar-akar $x_1$ dan $x_2$. Jika $x_1^2 + x_2^2 = 41$, nilai m yang memenuhi adalah ...", options: ["A. $m = -6$ atau $m = -4$", "B. $m = -6$ atau $m = 4$", "C. $m = 4$ atau $m = -3$", "D. $m = 3$ atau $m = 4$", "E. $m = -4$ atau $m = -3$"], jawaban: "B", pembahasan: "$x_1 + x_2 = -(m+1)$, $x_1 x_2 = -8$\n$x_1^2 + x_2^2 = (x_1+x_2)^2 - 2 x_1 x_2 = (m+1)^2 + 16$\n$(m+1)^2 + 16 = 41$\n$(m+1)^2 = 25$\n$m + 1 = \\pm 5$\n$m = 4$ atau $m = -6$. Jawaban B." },
  { no: 18, soal: "Jika nilai diskriminan persamaan kuadrat $2x^2 - 9x + c = 0$ adalah 121, maka $c$ = ...", options: ["A. -8", "B. -5", "C. 2", "D. 5", "E. 8"], jawaban: "B", pembahasan: "$D = b^2 - 4ac$\n$121 = (-9)^2 - 4(2)(c)$\n$121 = 81 - 8c$\n$8c = 81 - 121 = -40$\n$c = -5$. Jawaban B." },
  { no: 19, soal: "Persamaan $(p + 2)x^2 - 10x + 5 = 0$ mempunyai akar-akar kembar. Nilai p yang memenuhi adalah ...", options: ["A. 7", "B. 5", "C. 3", "D. -3"], jawaban: "C", pembahasan: "Akar-akar kembar berarti $D = 0$:\n$D = b^2 - 4ac = (-10)^2 - 4(p+2)(5) = 100 - 20(p+2)$\n$100 - 20p - 40 = 0$\n$60 = 20p$\n$p = 3$. Jawaban C." },
  { no: 20, soal: "Agar persamaan kuadrat $(m - 5)x^2 - 4x - 2 = 0$ mempunyai dua akar real, batas-batas nilai m yang memenuhi adalah ...", options: ["A. $m > 3$", "B. $m \\geq 3$", "C. $m < 3$", "D. $m > -3$"], jawaban: "B", pembahasan: "Dua akar real berarti $D \\geq 0$:\n$D = (-4)^2 - 4(m-5)(-2) = 16 + 8(m-5) = 8m - 24 \\geq 0$\n$8m \\geq 24 \\Rightarrow m \\geq 3$\nDengan syarat $m \\neq 5$ (agar tetap kuadrat), jawaban: $m \\geq 3$. Jawaban B." },
  { no: 21, soal: "Persamaan kuadrat yang akar-akarnya 5 dan -2 adalah ...", options: ["A. $x^2 + 3x - 10 = 0$", "B. $x^2 - 3x + 10 = 0$", "C. $x^2 - 3x - 10 = 0$", "D. $x^2 + 3x + 10 = 0$"], jawaban: "C", pembahasan: "Rumus: $x^2 - (x_1 + x_2)x + x_1 \\cdot x_2 = 0$\n$x_1 + x_2 = 5 + (-2) = 3$\n$x_1 \\cdot x_2 = 5 \\cdot (-2) = -10$\nPK: $x^2 - 3x - 10 = 0$. Jawaban C." },
  { no: 22, soal: "Jika 2 dan 3 akar-akar persamaan kuadrat, maka persamaan kuadrat yang dimaksud adalah ...", options: ["A. $x^2 + x + 5 = 0$", "B. $x^2 + 6x + 5 = 0$", "C. $x^2 + 5x - 6 = 0$", "D. $x^2 - 5x + 6 = 0$", "E. $x^2 + x + 5 = 0$"], jawaban: "D", pembahasan: "Akar 2 dan 3:\n$(x - 2)(x - 3) = 0$\n$x^2 - 5x + 6 = 0$. Jawaban D." },
  { no: 23, soal: "Persamaan yang akar-akarnya 3 lebihnya dari akar-akar persamaan $x^2 - x - 20 = 0$ adalah ...", options: ["A. $x^2 - 7x - 8 = 0$", "B. $x^2 - 7x + 8 = 0$", "C. $x^2 + 7x - 8 = 0$", "D. $x^2 - 7x - 8 = 0$"], jawaban: "A", pembahasan: "Cari akar lama: $x^2 - x - 20 = 0 \\Rightarrow (x-5)(x+4) = 0$\n$x_1 = 5, x_2 = -4$\nAkar baru (3 lebihnya): $5 + 3 = 8$ dan $-4 + 3 = -1$.\nJumlah baru: $8 + (-1) = 7$\nHasil kali baru: $8 \\cdot (-1) = -8$\nPK baru: $x^2 - 7x - 8 = 0$. Jawaban A." },
  { no: 24, soal: "Akar-akar persamaan $3x^2 - 12x + 2 = 0$ adalah $\\alpha$ dan $\\beta$. Persamaan kuadrat baru yang akar-akarnya $(\\alpha + 2)$ dan $(\\beta + 2)$ adalah ...", options: ["A. $3x^2 - 24x + 38 = 0$", "B. $3x^2 - 24x - 38 = 0$", "C. $3x^2 - 24x + 24 = 0$", "D. $3x^2 - 24x - 24 = 0$"], jawaban: "A", pembahasan: "Dari $3x^2 - 12x + 2 = 0$: $\\alpha + \\beta = 4$, $\\alpha\\beta = \\dfrac{2}{3}$\nAkar baru: $\\alpha + 2$ dan $\\beta + 2$.\nJumlah: $(\\alpha + 2) + (\\beta + 2) = 4 + 4 = 8$\nHasil kali: $(\\alpha + 2)(\\beta + 2) = \\alpha\\beta + 2(\\alpha + \\beta) + 4 = \\dfrac{2}{3} + 8 + 4 = \\dfrac{38}{3}$\nPK baru: $x^2 - 8x + \\dfrac{38}{3} = 0$\nKalikan 3: $3x^2 - 24x + 38 = 0$. Jawaban A." },
  { no: 25, soal: "Jika p dan q adalah akar-akar persamaan $x^2 - 5x - 1 = 0$, maka persamaan kuadrat baru yang akar-akarnya $2p + 1$ dan $2q + 1$ adalah ...", options: ["A. $x^2 + 10x + 11 = 0$", "B. $x^2 - 10x + 7 = 0$", "C. $x^2 - 12x + 7 = 0$", "D. $x^2 - 12x - 7 = 0$"], jawaban: "C", pembahasan: "$p + q = 5$, $pq = -1$\nAkar baru: $2p + 1$ dan $2q + 1$.\nJumlah: $(2p + 1) + (2q + 1) = 2(p + q) + 2 = 10 + 2 = 12$\nHasil kali: $(2p+1)(2q+1) = 4pq + 2(p+q) + 1 = -4 + 10 + 1 = 7$\nPK baru: $x^2 - 12x + 7 = 0$. Jawaban C." },
  { no: 26, soal: "Pak Musa mempunyai kebun berbentuk persegi panjang dengan luas 192 m². Selisih panjang dan lebarnya adalah 4 m. Apabila disekeliling kebun dibuat jalan dengan lebar 2 m, maka luas jalan tersebut adalah ... m².", options: ["A. 96", "B. 128", "C. 144", "D. 156"], jawaban: "B", pembahasan: "Misal lebar = $l$, panjang = $l + 4$.\nLuas: $l(l + 4) = 192$\n$l^2 + 4l - 192 = 0$\n$(l + 16)(l - 12) = 0$\n$l = 12$ (positif), maka panjang = 16.\nKebun + jalan: panjang baru = 16 + 4 = 20 m, lebar baru = 12 + 4 = 16 m.\nLuas total = $20 \\times 16 = 320$ m²\nLuas jalan = Luas total − luas kebun = $320 - 192 = 128$ m². Jawaban B." },
  { no: 27, soal: "Diketahui sebidang tanah berbentuk persegi panjang luasnya 72 m². Jika panjangnya tiga kali lebarnya, maka panjang diagonal bidang tersebut adalah ... m.", options: ["A. $6\\sqrt{6}$", "B. $4\\sqrt{15}$", "C. $4\\sqrt{30}$", "D. $6\\sqrt{15}$"], jawaban: "B", pembahasan: "Misal lebar = $x$, panjang = $3x$.\nLuas: $3x \\cdot x = 72 \\Rightarrow 3x^2 = 72 \\Rightarrow x^2 = 24$\n$x = \\sqrt{24} = 2\\sqrt{6}$\nLebar = $2\\sqrt{6}$, panjang = $6\\sqrt{6}$.\nDiagonal: $d = \\sqrt{p^2 + l^2} = \\sqrt{(6\\sqrt{6})^2 + (2\\sqrt{6})^2}$\n$= \\sqrt{216 + 24} = \\sqrt{240} = \\sqrt{16 \\cdot 15} = 4\\sqrt{15}$ m. Jawaban B." },
  { no: 28, soal: "Perhatikan gambar segitiga siku-siku berikut. Luas segitiga tersebut adalah ...", options: ["A. 30 cm²", "B. 60 cm²", "C. 32,5 cm²", "D. 78 cm²"], svgImage: <SvgSegitiga28 />, jawaban: "A", pembahasan: "Sisi-sisi segitiga: tegak $(x+2)$ dan $(x-5)$, miring $(x+3)$.\nTeorema Pythagoras:\n$(x-5)^2 + (x+2)^2 = (x+3)^2$\n$(x^2 - 10x + 25) + (x^2 + 4x + 4) = x^2 + 6x + 9$\n$2x^2 - 6x + 29 = x^2 + 6x + 9$\n$x^2 - 12x + 20 = 0$\n$(x - 10)(x - 2) = 0 \\Rightarrow x = 10$ (yang valid; $x = 2$ membuat sisi $x-5$ negatif).\nSisi tegak: $x - 5 = 5$ dan $x + 2 = 12$. Sisi miring: $x + 3 = 13$ (cek: $5^2 + 12^2 = 169 = 13^2$ ✓).\nLuas $= \\dfrac{1}{2} \\cdot 5 \\cdot 12 = 30$ cm². Jawaban A." },
  { no: 29, soal: "Dua bilangan cacah genap berurutan adalah p dan q. Jika $pq = 168$, maka nilai $(p + q)^2$ = ...", options: ["A. 324", "B. 676", "C. 484", "D. 900"], jawaban: "B", pembahasan: "Bilangan cacah genap berurutan: misal $p$, $q = p + 2$.\n$p(p + 2) = 168$\n$p^2 + 2p - 168 = 0$\n$(p + 14)(p - 12) = 0$\n$p = 12$ (positif), $q = 14$.\n$(p + q)^2 = (12 + 14)^2 = 26^2 = 676$. Jawaban B." },
];

const PersamaanKuadratPage = () => (
  <TKAPemantapanLayout
    title="PERSAMAAN KUADRAT"
    materiSections={materiSections}
    latihanDasar={latihanDasar}
  />
);

export default PersamaanKuadratPage;
