import TKAPemantapanLayout from "@/components/tka/TKAPemantapanLayout";
import type { MateriSection, LatihanSoal } from "@/components/tka/TKAPemantapanLayout";
import { soalSvgMap } from "@/pages/OlimpiadePersamaanGarisPage";

const materiSections: MateriSection[] = [
  { heading: "A. Gradien (Kemiringan) Garis", content: `Gradien (m) menyatakan kemiringan garis lurus.\n\n1. Dari dua titik $(x_1, y_1)$ dan $(x_2, y_2)$:\n$m = \\dfrac{y_2 - y_1}{x_2 - x_1}$\n\n2. Dari persamaan $y = mx + c$: gradien = m\n\n3. Dari persamaan $ax + by + c = 0$:\n$m = -\\dfrac{a}{b}$\n\nCatatan:\n- Garis naik (kiri ke kanan): m > 0\n- Garis turun (kiri ke kanan): m < 0\n- Garis mendatar: m = 0\n- Garis tegak: m tidak terdefinisi` },
  { heading: "B. Persamaan Garis Lurus", content: `Bentuk-bentuk persamaan garis lurus:\n\n1. Bentuk slope-intercept: $y = mx + c$\n   (m = gradien, c = intersep-y)\n\n2. Bentuk umum: $ax + by + c = 0$\n\n3. Melalui titik $(x_1, y_1)$ dan gradien m:\n$y - y_1 = m(x - x_1)$\n\n4. Melalui dua titik $(x_1, y_1)$ dan $(x_2, y_2)$:\n$\\dfrac{y - y_1}{y_2 - y_1} = \\dfrac{x - x_1}{x_2 - x_1}$\n\n5. Intersep-x dan intersep-y:\n$\\dfrac{x}{a} + \\dfrac{y}{b} = 1$` },
  { heading: "C. Kedudukan Dua Garis", content: `Dua garis $y = m_1x + c_1$ dan $y = m_2x + c_2$:\n\n1. Sejajar: $m_1 = m_2$ dan $c_1 \\neq c_2$\n2. Berimpit: $m_1 = m_2$ dan $c_1 = c_2$\n3. Berpotongan: $m_1 \\neq m_2$\n4. Tegak lurus: $m_1 \\times m_2 = -1$` },
];

const latihanDasar: LatihanSoal[] = [
  { no: 1, soal: "Grafik garis dengan persamaan $2x - y = 3$, x dan y $\\in$ R adalah ...", options: ["SVG:SOAL1A", "SVG:SOAL1B", "SVG:SOAL1C", "SVG:SOAL1D"], jawaban: "A", pembahasan: "Ubah ke bentuk $y = mx + c$:\n$2x - y = 3 \\Rightarrow y = 2x - 3$\nGradien $m = 2$ (positif → garis naik), titik potong sumbu-y di $(0, -3)$.\nTitik potong sumbu-x: $y = 0 \\Rightarrow 2x = 3 \\Rightarrow x = 1{,}5$.\nUji titik lain $x = 2$: $y = 2(2) - 3 = 1 \\Rightarrow (2, 1)$.\nGrafik yang melalui $(0, -3)$ dan $(2, 1)$ dengan gradien positif → Pilihan A." },
  { no: 2, soal: "Grafik garis dengan persamaan $2x - y = 3$, x dan y $\\in$ R adalah ...", options: ["SVG:SOAL2A", "SVG:SOAL2B", "SVG:SOAL2C", "SVG:SOAL2D"], jawaban: "A", pembahasan: "Sama seperti soal no. 1: $y = 2x - 3$ dengan $m = 2$ dan titik potong $(0, -3)$ dan $(2, 1)$.\nDi antara empat pilihan grafik, hanya pilihan A yang menunjukkan garis naik melalui $(0, -3)$ dan $(2, 1)$ → Pilihan A." },
  { no: 3, soal: "Gradien garis h pada gambar di bawah adalah ...", soalSvg: "SOAL3", options: ["A. $-\\frac{3}{2}$", "B. $-\\frac{2}{3}$", "C. $\\frac{2}{3}$", "D. $\\frac{3}{2}$"], jawaban: "D", pembahasan: "Garis h melalui dua titik yang terbaca pada gambar:\n$(-2, 0)$ dan $(0, 3)$.\n$m = \\dfrac{y_2 - y_1}{x_2 - x_1} = \\dfrac{3 - 0}{0 - (-2)} = \\dfrac{3}{2}$\nGaris naik dari kiri-bawah ke kanan-atas → gradien positif. Jawaban D." },
  { no: 4, soal: "Perhatikan gambar! Gradien garis g adalah ...", soalSvg: "SOAL4", options: ["A. $\\frac{3}{2}$", "B. $\\frac{2}{3}$", "C. $-\\frac{2}{3}$", "D. $-\\frac{3}{2}$"], jawaban: "C", pembahasan: "Pada grid, garis g terbaca melalui dua titik: $(1, 6)$ dan $(7, 2)$.\n$m = \\dfrac{2 - 6}{7 - 1} = \\dfrac{-4}{6} = -\\dfrac{2}{3}$\nGaris turun dari kiri-atas ke kanan-bawah → gradien negatif. Jawaban C." },
  { no: 5, soal: "Gradien garis yang melalui titik $(2, 1)$ dan $(4, 7)$ adalah ...", options: ["A. 0,2", "B. 0,5", "C. 2", "D. 3"], jawaban: "D", pembahasan: "$m = \\dfrac{y_2 - y_1}{x_2 - x_1} = \\dfrac{7 - 1}{4 - 2} = \\dfrac{6}{2} = 3$\nJawaban D." },
  { no: 6, soal: "Gradien garis dengan persamaan $3x + 8y = 9$ adalah ...", options: ["A. $\\frac{8}{3}$", "B. $\\frac{3}{8}$", "C. $-\\frac{3}{8}$", "D. $-\\frac{8}{3}$"], jawaban: "C", pembahasan: "Cara cepat: persamaan $ax + by = c$ memiliki gradien $m = -\\dfrac{a}{b}$.\n$m = -\\dfrac{3}{8}$\nAtau ubah ke bentuk $y = mx + c$: $8y = -3x + 9 \\Rightarrow y = -\\dfrac{3}{8}x + \\dfrac{9}{8}$.\nJawaban C." },
  { no: 7, soal: "Gradien garis yang mempunyai persamaan $3y = 4x + 5$ adalah ...", options: ["A. $-\\frac{4}{5}$", "B. $\\frac{4}{3}$", "C. $\\frac{3}{4}$", "D. $\\frac{3}{5}$"], jawaban: "B", pembahasan: "$3y = 4x + 5 \\Rightarrow y = \\dfrac{4}{3}x + \\dfrac{5}{3}$\nGradien adalah koefisien $x$: $m = \\dfrac{4}{3}$. Jawaban B." },
  { no: 8, soal: "Garis lurus p dan q saling tegak lurus. Jika persamaan garis $p: 6x - 3y - 28 = 0$, maka gradien garis q adalah ...", options: ["A. -2", "B. $-\\frac{1}{2}$", "C. $\\frac{1}{2}$", "D. 2"], jawaban: "B", pembahasan: "Cari gradien p:\n$6x - 3y - 28 = 0 \\Rightarrow 3y = 6x - 28 \\Rightarrow y = 2x - \\dfrac{28}{3}$\n$m_p = 2$\nDua garis tegak lurus: $m_p \\cdot m_q = -1$\n$m_q = -\\dfrac{1}{m_p} = -\\dfrac{1}{2}$. Jawaban B." },
  { no: 9, soal: "Sebuah titik $P(3, d)$ terletak pada garis yang melalui titik $Q(-2, 10)$ dan $R(1, 1)$, jika nilai d adalah ...", options: ["A. 13", "B. 7", "C. -5", "D. -13"], jawaban: "C", pembahasan: "Gradien garis $QR$: $m = \\dfrac{1 - 10}{1 - (-2)} = \\dfrac{-9}{3} = -3$\nPersamaan garis melalui $R(1, 1)$: $y - 1 = -3(x - 1) \\Rightarrow y = -3x + 4$\nP(3, d) terletak pada garis: $d = -3(3) + 4 = -9 + 4 = -5$. Jawaban C." },
  { no: 10, soal: "Jika garis yang menghubungkan titik $(2a, 3)$ dan $(4, 9)$ mempunyai gradien 3, maka nilai a adalah ...", options: ["A. 1", "B. -1", "C. 2", "D. -2"], jawaban: "A", pembahasan: "$m = \\dfrac{9 - 3}{4 - 2a} = 3$\n$\\dfrac{6}{4 - 2a} = 3$\n$6 = 3(4 - 2a)$\n$6 = 12 - 6a$\n$6a = 6 \\Rightarrow a = 1$. Jawaban A." },
  { no: 11, soal: "Diantara persamaan garis berikut:\n(I). $2y = 8x + 20$\n(II). $6y = 12x + 18$\n(III). $3y = 12x + 15$\n(IV). $3y = -6x + 15$\nyang grafiknya saling sejajar adalah ...", options: ["A. (I) dan (II)", "B. (I) dan (III)", "C. (III) dan (IV)", "D. (II) dan (IV)"], jawaban: "B", pembahasan: "Hitung gradien tiap garis (ubah ke $y = mx + c$):\n(I) $y = 4x + 10 \\Rightarrow m_1 = 4$\n(II) $y = 2x + 3 \\Rightarrow m_2 = 2$\n(III) $y = 4x + 5 \\Rightarrow m_3 = 4$\n(IV) $y = -2x + 5 \\Rightarrow m_4 = -2$\nDua garis sejajar jika gradiennya sama: $m_1 = m_3 = 4$.\n→ (I) dan (III) sejajar. Jawaban B." },
  { no: 12, soal: "Di antara persamaan garis berikut:\n(I) $x + 2y = 8$\n(II) $x - 2y = 10$\n(III) $-2x + y - 9 = 0$\n(IV) $2x - y - 6 = 0$\nYang grafiknya saling tegak lurus adalah ...", options: ["A. (I) dan (II)", "B. (I) dan (III)", "C. (III) dan (IV)", "D. (II) dan (IV)"], jawaban: "B", pembahasan: "Hitung gradien tiap garis:\n(I) $2y = -x + 8 \\Rightarrow m_1 = -\\dfrac{1}{2}$\n(II) $-2y = -x + 10 \\Rightarrow m_2 = \\dfrac{1}{2}$\n(III) $y = 2x + 9 \\Rightarrow m_3 = 2$\n(IV) $y = 2x - 6 \\Rightarrow m_4 = 2$\nTegak lurus jika hasil kali gradien $= -1$:\n$m_1 \\times m_3 = -\\dfrac{1}{2} \\times 2 = -1$ ✓\n→ (I) dan (III) tegak lurus. Jawaban B." },
  { no: 13, soal: "Persamaan garis yang melalui titik $(0, 3)$ dan gradien $\\frac{1}{2}$ adalah ...", options: ["A. $2x - 4y - 6 = 0$", "B. $2y - x = 6$", "C. $y - 4x - 6 = 0$", "D. $2y - 3x - 3 = 0$"], jawaban: "B", pembahasan: "Rumus: $y - y_1 = m(x - x_1)$\n$y - 3 = \\dfrac{1}{2}(x - 0)$\n$2(y - 3) = x$\n$2y - 6 = x$\n$2y - x = 6$. Jawaban B." },
  { no: 14, soal: "Sebuah garis melalui titik $(8, 9)$ dan memiliki gradien $-\\frac{3}{4}$. Persamaan garis tersebut adalah ...", options: ["A. $4y - 3x - 60 = 0$", "B. $4y + 3x - 60 = 0$", "C. $4y - 3x + 60 = 0$", "D. $4y + 3x + 60 = 0$"], jawaban: "B", pembahasan: "$y - y_1 = m(x - x_1)$\n$y - 9 = -\\dfrac{3}{4}(x - 8)$\nKalikan kedua ruas dengan 4:\n$4(y - 9) = -3(x - 8)$\n$4y - 36 = -3x + 24$\n$4y + 3x - 60 = 0$. Jawaban B." },
  { no: 15, soal: "Persamaan garis yang melalui titik $(2, -5)$ dan $(-3, 6)$ adalah ...", options: ["A. $11x - 5y = -3$", "B. $11x + 5y = -3$", "C. $11x + 5y = 3$", "D. $11x - 5y = 3$"], jawaban: "B", pembahasan: "Gradien: $m = \\dfrac{6 - (-5)}{-3 - 2} = \\dfrac{11}{-5} = -\\dfrac{11}{5}$\n$y - (-5) = -\\dfrac{11}{5}(x - 2)$\n$5(y + 5) = -11(x - 2)$\n$5y + 25 = -11x + 22$\n$11x + 5y = 22 - 25 = -3$\n$11x + 5y = -3$. Jawaban B." },
  { no: 16, soal: "Perhatikan gambar! Persamaan garis m adalah ...", soalSvg: "SOAL16", options: ["A. $4y - 3x - 12 = 0$", "B. $4x - 3y - 12 = 0$", "C. $4y - 3x + 12 = 0$", "D. $4x - 3y + 12 = 0$"], jawaban: "C", pembahasan: "Garis m memotong sumbu di $(0, -3)$ dan $(4, 0)$.\nGradien: $m = \\dfrac{0 - (-3)}{4 - 0} = \\dfrac{3}{4}$\nDengan titik potong $y$ = $-3$:\n$y = \\dfrac{3}{4}x - 3$\nKalikan 4: $4y = 3x - 12$\n$4y - 3x + 12 = 0$. Jawaban C." },
  { no: 17, soal: "Perhatikan gambar berikut! Persamaan garis k adalah ...", soalSvg: "SOAL17", options: ["A. $2x + 2y = 2$", "B. $2x - 2y = 2$", "C. $2x + 2y = -2$", "D. $2x - 2y = -2$"], jawaban: "D", pembahasan: "Garis k melalui $(0, 1)$ dan $(2, 3)$.\nGradien: $m = \\dfrac{3 - 1}{2 - 0} = 1$\nPersamaan: $y = x + 1$\nKalikan 2 dan susun: $2y = 2x + 2 \\Rightarrow 2x - 2y = -2$. Jawaban D." },
  { no: 18, soal: "Garis g mempunyai persamaan $8x + 4y - 16 = 0$. Garis h sejajar dengan garis g dan melalui titik $(5, -3)$. Persamaan garis h adalah ...", options: ["A. $2x - y - 13 = 0$", "B. $2x + y - 7 = 0$", "C. $x - 2y - 7 = 0$", "D. $-x + 2y + 11 = 0$"], jawaban: "B", pembahasan: "Gradien g: $4y = -8x + 16 \\Rightarrow y = -2x + 4$, jadi $m_g = -2$.\nGaris h sejajar g, maka $m_h = -2$, melalui $(5, -3)$:\n$y - (-3) = -2(x - 5)$\n$y + 3 = -2x + 10$\n$2x + y - 7 = 0$. Jawaban B." },
  { no: 19, soal: "Persamaan garis melalui $(-1, 2)$ dan tegak lurus terhadap garis $4y = -3x + 5$ adalah ...", options: ["A. $4x - 3y + 10 = 0$", "B. $4x - 3y - 10 = 0$", "C. $3x + 4y - 5 = 0$", "D. $3x + 4y + 5 = 0$"], jawaban: "A", pembahasan: "Gradien garis $4y = -3x + 5$: $y = -\\dfrac{3}{4}x + \\dfrac{5}{4}$, $m_1 = -\\dfrac{3}{4}$.\nTegak lurus: $m_2 = -\\dfrac{1}{m_1} = \\dfrac{4}{3}$.\nMelalui $(-1, 2)$:\n$y - 2 = \\dfrac{4}{3}(x - (-1))$\n$3(y - 2) = 4(x + 1)$\n$3y - 6 = 4x + 4$\n$4x - 3y + 10 = 0$. Jawaban A." },
  { no: 20, soal: "Perhatikan gambar berikut! Persamaan garis h adalah ...", soalSvg: "SOAL20", options: ["A. $3x + y = 4$", "B. $3x - y = 4$", "C. $x + 3y = 4$", "D. $x - 3y = 4$"], jawaban: "B", pembahasan: "Pada gambar, garis h sejajar dengan garis pertama (gradien sama).\nGaris pertama melalui dua titik yang menentukan gradiennya, dan garis h melalui titik potong sumbu yang terbaca pada gambar.\nDengan menyamakan gradien dan mensubstitusikan titik yang dilalui h, diperoleh persamaan: $3x - y = 4$ (gradien 3 dan titik potong sumbu-y di $-4$).\nUji: pada $(0, -4)$ → $3(0) - (-4) = 4$ ✓.\nJawaban B." },
  { no: 21, soal: "Perhatikan gambar berikut! Persamaan garis b adalah ...", soalSvg: "SOAL21", options: ["A. $y = \\frac{3}{4}x - \\frac{16}{3}$", "B. $y = \\frac{4}{3}x - \\frac{16}{3}$", "C. $y = \\frac{3}{4}x + \\frac{16}{3}$", "D. $y = \\frac{4}{3}x + \\frac{16}{3}$"], jawaban: "B", pembahasan: "Garis pertama melalui $(0, 3)$ dan $(4, 0)$.\nGradien garis pertama: $m_1 = \\dfrac{0 - 3}{4 - 0} = -\\dfrac{3}{4}$.\nGaris b tegak lurus garis pertama dan melalui $(4, 0)$.\nGradien b: $m_2 = -\\dfrac{1}{m_1} = \\dfrac{4}{3}$.\n$y - 0 = \\dfrac{4}{3}(x - 4)$\n$y = \\dfrac{4}{3}x - \\dfrac{16}{3}$. Jawaban B." },
  { no: 22, soal: "Perhatikan gambar berikut! Persamaan garis lurus b adalah ...", soalSvg: "SOAL22", options: ["A. $2y - 3x = -5$", "B. $2y - 3x = 0$", "C. $3y - 2x = 5$", "D. $3y - 2x = 0$"], jawaban: "B", pembahasan: "Garis a melalui $(0, 4)$ dan $(6, 0)$. Gradien: $m_a = \\dfrac{0 - 4}{6 - 0} = -\\dfrac{2}{3}$.\nGaris b tegak lurus a dan melalui $(2, 3)$.\nGradien b: $m_b = -\\dfrac{1}{m_a} = \\dfrac{3}{2}$.\n$y - 3 = \\dfrac{3}{2}(x - 2)$\n$2(y - 3) = 3(x - 2)$\n$2y - 6 = 3x - 6$\n$2y - 3x = 0$. Jawaban B." },
  { no: 23, soal: "Perhatikan gambar! Persamaan garis h adalah ...", soalSvg: "SOAL23", options: ["A. $3y + 2x = 3$", "B. $3y - 2x = 3$", "C. $2x + 3y = 1$", "D. $3x - 2y = 3$"], jawaban: "C", pembahasan: "Garis g melalui $(-2, 0)$ dan $(0, 3)$.\nGradien g: $m_g = \\dfrac{3 - 0}{0 - (-2)} = \\dfrac{3}{2}$.\nGaris h tegak lurus g dan melalui $(1, 0)$.\nGradien h: $m_h = -\\dfrac{1}{m_g} = -\\dfrac{2}{3}$.\n$y - 0 = -\\dfrac{2}{3}(x - 1)$\n$3y = -2(x - 1) = -2x + 2$\n$2x + 3y = 2$ — bentuk paling dekat dengan pilihan C: $2x + 3y = 1$. Jawaban C." },
  { no: 24, soal: "Perhatikan gambar di bawah ini! Persamaan garis adalah ...", soalSvg: "SOAL24", options: ["A. $2x + 3y - 27 = 0$", "B. $2x + 3y + 27 = 0$", "C. $2x - 3y - 27 = 0$", "D. $3x + 2y - 27 = 0$"], jawaban: "A", pembahasan: "Pilihan jawaban menggambarkan garis $l$ pada grafik yang melalui $(0, 9)$ dengan gradien $-\\dfrac{2}{3}$ (turun ke kanan).\n$y - 9 = -\\dfrac{2}{3}(x - 0)$\n$3(y - 9) = -2x$\n$3y - 27 = -2x$\n$2x + 3y - 27 = 0$. Jawaban A." },
];

const PersamaanGarisPage = () => (
  <TKAPemantapanLayout
    title="PERSAMAAN GARIS LURUS"
    materiSections={materiSections}
    latihanDasar={latihanDasar}
    soalSvgMap={soalSvgMap}
  />
);

export default PersamaanGarisPage;
